apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan  # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # All the pods from any node in the openshift cluster can read & write this external storage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.200  # In case you are working on second server, you need to change this to 192.168.10.202
    path: /var/nfs/jegan/mysql  # Replace jegan with your linux user
